---
# Note
#
# Each rule can only have one single action section.
# If you need to run multiple actions when a rule is matched,
# either configure multiple rules, or create a workflow, and call that.
name: "hello"
pack: "mawi_ifttt"
description: "listen on slack and help me if you can"
enabled: true

trigger:
    type: "slack.message"

criteria:
    trigger.text:
        type: "iregex"
        pattern : "jenkinsfile"
    trigger.channel.name:
        type: "regex"
        pattern: "(woot-ci|automation-dev)"

action:
    ref: "mawi_ifttt.slack_help"
    parameters:
        trigger_text: "{{ trigger.text }}"
        trigger_user_name: "{{ trigger.user.name }}"
        trigger_channel_name: "{{ trigger.channel.name }}"
